# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "30 0 * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "set up python"
        uses: actions/setup-python@master
        with:
          python-version: 3.9

      - name: install requests
        run: |
          python -m pip install requests

      - name: run App
        env:
          USERNAME: ${{ secrets.XB_USERNAME }}
          PASSWORD: ${{ secrets.XB_PASSWORD }}
          LOCATION: ${{secrets.XB_LOCATION}}
          COORD: ${{secrets.XB_COORD}}
          IS_EMAIL: ${{secrets.XB_IS_EMAIL}}
          EMAIL: ${{secrets.XB_EMAIL}}
          E_HOST: ${{secrets.XB_E_HOST}}
          E_ACCOUNT: ${{secrets.XB_E_ACCOUNT}}
          E_PASS: ${{secrets.XB_E_PASS}}
        run: |
          python3.9 main.py
